project: 
  type: website

website:
  title: "Jacob Hill"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  repo-url: https://github.com/jacob-l-hill/jacb-l-hill.github.io
  #repo-actions: [issue] #if you want to allow others to report issues on your site uncomment this line

  page-footer: 
    border: true
    left: "Jacob Hill 2024©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/jacob-l-hill/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "Resume"
        file: resume.qmd
      - text: "About Me"
        file: about_me.qmd
      - text: "Story Time"
        file: story_time.qmd
      - text: "Something Cool Here"
        file: something_cool.qmd
  
  # learn more about navigation here https://quarto.org/docs/websites/website-navigation.html
  # comment out any of the sections below to turn off the sidebar

  sidebar: 
    - title: "About Me"
      style: "docked"
      background: light
      contents:
        - text: "Data Cleansing"
          file: cleansing.qmd
        - text: "---"
        - text: "Project 1"
          file: Cleansing_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Cleansing_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Cleansing_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Cleansing_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Cleansing_Projects/project5.qmd
        - text: "---"
    - title: "Story Time"
      style: "docked"
      background: light
      contents:
        - text: "Data Exploration"
          file: exploration.qmd
        - text: "---"
        - text: "Project 1"
          file: Exploration_Projects/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Exploration_Projects/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Exploration_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Exploration_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Exploration_Projects/project5.qmd
        - text: "---"
    - title: "Something Cool Here"
      style: "docked"
      background: light
      contents:
        - text: "Story Telling"
          file: story_telling.qmd
        - text: "---"
        - text: "Project 1"
          file: Story_Telling/project1.qmd
        - text: "---"
        - text: "Project 2"
          file: Story_Telling/project2.qmd
        - text: "---"
        - text: "Project 3"
          file: Story_Telling/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: Story_Telling/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: Story_Telling/project5.qmd
        - text: "---"
  
format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: journal # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: slate
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



